services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      - PMA_HOST= # Replace with your hosted DB hostname
      - PMA_PORT=25060
      - PMA_USER=doadmin                             # Replace with the correct username if needed
      - PMA_PASSWORD=     # Replace with the correct password
    ports:
      - "8080:80"
    networks:
      - travelnetwork

networks:
  travelnetwork:
    driver: bridge
