services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      - PMA_PORT=25060
      - PMA_USER=doadmin                             # Replace with the correct username if needed
    ports:
      - "8080:80"
    networks:
      - travelnetwork

networks:
  travelnetwork:
    driver: bridge
